---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: clusterrepos
  namespace: fleet-default
spec:
  repo: git@github.com:eluminare/fleet-apps.git
  clientSecretName: github-sshkey
  branch: main
  paths:
  - cluster-repos/
  targets:
  - clusterSelector: {}
