---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: clusterrepos
  namespace: fleet-default
spec:
  repo: https://github.com/eluminare/fleet-apps
  branch: main
  paths:
  - cluster-repos/
  targets:
  - clusterSelector: {}
