---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: gitlab-operator
  namespace: fleet-default
spec:
  repo: https://github.com/eluminare/fleet-apps
  branch: main
  paths:
  - gitlab-operator/
  targets:
  - clusterSelector: {}