---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: infra-manifests
  namespace: fleet-default
spec:
  repo: https://github.com/eluminare/fleet-apps
  branch: main
  paths:
  - infra-manifests/
  targets:
  - clusterSelector: {}