---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: rancher-monitoring
  namespace: fleet-default
spec:
  repo: https://github.com/eluminare/fleet-apps
  branch: main
  paths:
  - helm/rancher-monitoring
  targets:
  - clusterSelector: {}
---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: rancher-monitoring-crd
  namespace: fleet-default
spec:
  repo: https://github.com/eluminare/fleet-apps
  branch: main
  paths:
  - helm/rancher-monitoring-crd
  targets:
  - clusterSelector: {}