---
apiVersion: v1
kind: Service
metadata:
  name: office
  namespace: office
  annotations:
    traefik.backend.circuitbreaker: "NetworkErrorRatio() > 0.5"
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: office