apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: subsonic-test.familie-keller.info
  namespace: cert-manager
spec:
  dnsNames:
  - subsonic-test.familie-keller.info
  issuerRef:
    kind: ClusterIssuer
    name: certmanager-azure-familie-keller
  secretName: subsonic-test.familie-keller.info-tls