---
apiVersion: v1
kind: Service
metadata:
  name: subsonic
  annotations:
    traefik.backend.circuitbreaker: "NetworkErrorRatio() > 0.5"
spec:
  ports:
  - name: http
    targetPort: 4040
    port: 4040
  selector:
    app: subsonic
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: subsonic
#  annotations:
#    kubernetes.io/ingress.class: traefik
#    certmanager.k8s.io/issuer: "certmanager-azure"
#    certmanager.k8s.io/acme-challenge-type: "dns01"
#    ingress.kubernetes.io/ssl-redirect: "true"
#spec:
#  rules:
#  - host: subsonic.services.k3s.microserver.ovh
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: subsonic
#          servicePort: http
#  tls:
#    - hosts:
#        - subsonic.services.k3s.microserver.ovh
#      secretName: subsonic.services.k3s.microserver.ovh-tls
#---
#apiVersion: cert-manager.io/v1alpha2
#kind: Certificate
#metadata:
#  name: subsonic.services.k3s.microserver.ovh-dns
#  namespace: default
#spec:
#  secretName: subsonic.services.k3s.microserver.ovh-tls
#  issuerRef:
#    name: certmanager-azure
#  dnsNames:
#    - subsonic.services.k3s.microserver.ovh