---
apiVersion: v1
kind: Service
metadata:
  name: subsonic
  annotations:
    traefik.backend.circuitbreaker: "NetworkErrorRatio() > 0.5"
spec:
  ports:
  - name: http
    targetPort: 4040
    port: 4040
  selector:
    app: subsonic
