---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: subsonic-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/S01/K3S/subsonic
    server: 192.168.150.94
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: subsonic
    name: subsonic-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: subsonic-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/S01/Musik
    server: 192.168.1.148
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: subsonic
    name: subsonic-music-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: subsonic-music-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  