---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: subsonic-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/S01/K3S/subsonic
    server: 192.168.150.94
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: subsonic-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: subsonic-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
