apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: subsonic
  namespace: subsonic
spec:
  rules:
  - host: subsonic-test.familie-keller.info
    http:
      paths:
      - backend:
          service:
            name: subsonic
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - subsonic-test.familie-keller.info
    secretName: subsonic-test.familie-keller.info-tls